// Generated by 'Export TypeScript Sprites' Aseprite Extension
import url from "./sprites.png"
export const horse = { pivot: { x: 7, y: 12, }, y: 0, url, w: 128, h: 16, x: 0, };
export const rider = { pivot: { x: 7, y: 12, }, y: 16, url, w: 128, h: 16, x: 0, };
export const shadow = { pivot: { x: 7, y: 3, }, y: 57, url, w: 16, h: 7, x: 16, };
export const waypoint = { y: 48, url, w: 4, h: 3, x: 0, };
export const flag = { pivot: { x: 3, y: 17, }, y: 46, url, w: 7, h: 18, x: 8, };
export const grass_1 = { y: 74, url, w: 32, h: 6, x: 0, };
export const grass_2 = { y: 74, url, w: 15, h: 6, x: 32, };
export const grass_3 = { y: 74, url, w: 4, h: 6, x: 48, };
export const grass_4 = { y: 74, url, w: 7, h: 6, x: 52, };
export const rocks = { y: 69, url, w: 30, h: 5, x: 0, };
export const font = { y: 90, url, w: 160, h: 22, x: 0, };
export const javelin_1 = { pivot: { x: 3, y: 3, }, y: 68, url, w: 6, h: 6, x: 32, };
export const javelin_2 = { pivot: { x: 4, y: 3, }, y: 68, url, w: 8, h: 6, x: 38, };
export const javelin_3 = { pivot: { x: 3, y: 3, }, y: 68, url, w: 6, h: 6, x: 46, };
export const javelin_4 = { pivot: { x: 3, y: 6, }, y: 68, url, w: 7, h: 6, x: 52, };
export const rock_1 = { y: 60, url, w: 18, h: 20, x: 89, };
export const rock_2 = { y: 72, url, w: 10, h: 8, x: 108, };
export const rock_3 = { y: 67, url, w: 15, h: 13, x: 119, };
export const rock_4 = { y: 69, url, w: 10, h: 11, x: 134, };
export const rock_5 = { y: 68, url, w: 16, h: 12, x: 144, };
export const unit_indicator = { pivot: { x: 7, y: 4, }, y: 48, url, w: 16, h: 9, x: 16, };