// Generated by 'Export TypeScript Sprites' Aseprite Extension
import url from "./sprites.png"
export const horse = { w: 128, x: 0, pivot: { y: 10, x: 7, }, url, y: 20, h: 14, };
export const rider = { w: 128, x: 0, pivot: { y: 11, x: 7, }, url, y: 34, h: 12, };
export const shadow = { w: 16, x: 0, pivot: { y: 2, x: 7, }, url, y: 46, h: 7, };
export const flag = { w: 7, x: 0, pivot: { y: 17, x: 3, }, url, y: 53, h: 18, };
export const grass_1 = { w: 32, x: 16, url, y: 46, h: 6, };
export const grass_2 = { w: 15, x: 48, url, y: 46, h: 6, };
export const grass_3 = { w: 4, x: 63, url, y: 46, h: 6, };
export const grass_4 = { w: 7, x: 67, url, y: 46, h: 6, };
export const dirt = { w: 30, x: 74, url, y: 46, h: 6, };
export const font = { w: 160, x: 0, url, y: -1, h: 21, };
export const javelin_1 = { w: 6, x: 104, pivot: { y: 1, x: 3, }, url, y: 46, h: 3, };
export const javelin_2 = { w: 8, x: 104, pivot: { y: 0, x: 4, }, url, y: 49, h: 1, };
export const javelin_3 = { w: 6, x: 110, pivot: { y: 1, x: 3, }, url, y: 46, h: 3, };
export const javelin_4 = { w: 3, x: 116, pivot: { y: 3, x: 3, }, url, y: 46, h: 3, };
export const rock_1 = { w: 18, x: 142, url, y: 20, h: 18, };
export const rock_2 = { w: 10, x: 132, url, y: 30, h: 8, };
export const rock_3 = { w: 16, x: 144, url, y: 38, h: 12, };
export const rock_4 = { w: 10, x: 132, url, y: 20, h: 10, };
export const rock_5 = { w: 16, x: 128, url, y: 38, h: 13, };