// Generated by 'Export TypeScript Sprites' Aseprite Extension
import url from "./sprites.png"
export const horse = { w: 128, x: 0, pivot: { y: 10, x: 7, }, url, y: 0, h: 14, };
export const rider = { w: 128, x: 0, pivot: { y: 11, x: 7, }, url, y: 14, h: 12, };
export const shadow = { w: 16, x: 0, pivot: { y: 2, x: 7, }, url, y: 26, h: 7, };
export const flag = { w: 7, x: 0, pivot: { y: 17, x: 3, }, url, y: 33, h: 18, };
export const grass_1 = { w: 32, x: 16, url, y: 26, h: 6, };
export const grass_2 = { w: 15, x: 48, url, y: 26, h: 6, };
export const grass_3 = { w: 4, x: 63, url, y: 26, h: 6, };
export const grass_4 = { w: 7, x: 67, url, y: 26, h: 6, };
export const dirt = { w: 30, x: 74, url, y: 26, h: 6, };
export const rock_1 = { w: 18, x: 142, url, y: 0, h: 18, };
export const rock_2 = { w: 10, x: 132, url, y: 10, h: 8, };
export const rock_3 = { w: 16, x: 144, url, y: 18, h: 12, };
export const rock_4 = { w: 10, x: 132, url, y: 0, h: 10, };
export const rock_5 = { w: 16, x: 128, url, y: 18, h: 13, };
export const javelin = { w: 56, x: 7, pivot: { y: 3, x: 3, }, url, y: 33, h: 7, };
export const skull = { w: 5, x: 7, pivot: { y: 4, x: 2, }, url, y: 40, h: 6, };
export const horde_indicator = { w: 4, x: 12, pivot: { y: 2, x: 2, }, url, y: 40, h: 4, };
export const stone_circle = { w: 20, x: 140, url, y: 32, h: 16, };
export const unit_indicator = { w: 1, x: 13, url, y: 41, h: 1, };
export const yurt = { w: 34, x: 40, pivot: { y: 14, x: 17, }, url, y: 43, h: 21, };
export const standing_stone = { w: 9, x: 7, pivot: { y: 14, x: 4, }, url, y: 46, h: 17, };
export const banner = { w: 11, x: 74, pivot: { y: 20, x: 5, }, url, y: 40, h: 25, };
export const totem_1 = { w: 9, x: 144, pivot: { y: 10, x: 4, }, url, y: 49, h: 11, };
export const totem_2 = { w: 5, x: 128, pivot: { y: 18, x: 2, }, url, y: 31, h: 19, };
export const well = { w: 12, x: 27, pivot: { y: 9, x: 6, }, url, y: 49, h: 14, };